#!/bin/bash

# Create a new bedrock server instance

# Usage: ./new <instance name>
#
#   <instance name>
#     Name that will be used as the systemd service name in the form of `mcbs-<instance name>` and
#     in the `./instances` and `./run` directories for the new bedrock server instance. This argument
#     will be converted to lowercase and it's whitespace trimmed.

# Script arguments.
instance_name=$1

# Abort if <instance name> already exists in instances directory.
instance_name="$(echo "$instance_name" | awk '{print tolower($0)}')"
instance_name="$(echo -e "${instance_name}" | tr -d '[[:space:]]')"

if [ -d "instances/${instance_name}" ]; then
  echo "Directory ./instances/${instance_name}/ already exists, use another instance name or delete with:"
  echo ""
  echo "  rm -rf ./instances/${instance_name}"
  echo ""
  exit 1
fi


# Fetch current bedrock server download url.
echo "Trying to fetch minecraft.net bedrock server url..."

url="$(curl -s https://www.minecraft.net/en-us/download/server/bedrock | grep -P '(https:\/\/.+linux.+\.zip)' -o)"
filename="$(echo $url | grep -P '(bedrock-server.+\.zip)' -o)"

echo "url: [${url}]"
echo "filename: [${filename}]"
echo ""


# Download current bedrock server or skip if already downloaded.
if [ -f "cache/${filename}" ]; then
  echo "${filename} exists in cache directory, download will be skipped."
else
  echo "Download start..."
  wget $url -q -P cache/
  echo "Download finished."
fi


# Create ./instances/ and ./run/ if not exists.
if [ ! -d instances ]; then
  mkdir instances
fi

if [ ! -d run ]; then
  mkdir run
fi


# Prepare directory to run instance at ./run/<instance name>
# Extract bedrock server zip file to ./run/<instance name>
# Create launcher script for instance.
rm -rf "run/${instance_name}"
mkdir "run/${instance_name}"

echo "Extracting ${filename} to ./run/${instance_name}/"

unzip -qq "cache/${filename}" -d "run/${instance_name}/"

echo "Finished extraction."

cat > "run/${instance_name}/bedrock_server.sh" <<- EOM
#!/bin/bash
cd "\${0%/*}"
LD_LIBRARY_PATH=. ./bedrock_server
EOM

chmod 755 "run/${instance_name}/bedrock_server.sh"
run_user="$(stat -c "%U" "run/${instance_name}/bedrock_server")"
run_path="$(readlink -f "run/${instance_name}")"
exec_path="$(readlink -f "run/${instance_name}/bedrock_server")"



# Create directory for instance files at ./instances/<instance name>
# Create bedrock server files
# Create systemd service unit file.
mkdir "instances/${instance_name}"
mkdir "instances/${instance_name}/worlds"

echo "Creating bedrock server files at .instances/${instance_name}/"

cp "run/${instance_name}/permissions.json" "instances/${instance_name}/permissions.json"
cp "run/${instance_name}/server.properties" "instances/${instance_name}/server.properties"
cp "run/${instance_name}/whitelist.json" "instances/${instance_name}/whitelist.json"

cat > "instances/${instance_name}/mcbs-${instance_name}.service" <<- EOM
[Unit]
Description=Minecraft Bedrock Server Instance (${instance_name})
After=network.target
After=systemd-user-sessions.service
After=network-online.target

[Service]
Type=simple
User=$run_user
WorkingDirectory=$run_path
Environment=LD_LIBRARY_PATH=.
ExecStart=$exec_path

[Install]
WantedBy=multi-user.target
EOM


# Save the current minecraft bedrock server version
printf "%s" "$filename" > "instances/${instance_name}/running-version"


# Link instance files to run directory.
echo "Linking instance files to run directory..."

ln -rsf "instances/${instance_name}/worlds" "run/${instance_name}/worlds"

ln -rsf "instances/${instance_name}/permissions.json" "run/${instance_name}/permissions.json"
ln -rsf "instances/${instance_name}/server.properties" "run/${instance_name}/server.properties"
ln -rsf "instances/${instance_name}/whitelist.json" "run/${instance_name}/whitelist.json"


# Configure the new Bedrock Server instance
PS3="?"
echo ""
echo "New instance server.properties configuration"

read -p 'Server name: ' server_name

echo "Game mode:"
select game_mode in "survival" "creative" "adventure";

echo "Difficulty:"
select difficulty in "peaceful" "easy" "normal" "hard";

echo "Allow cheats:"
select allow_cheats in "false" "true";

read -p 'Server IPv4 port: ' server_port
read -p 'Server IPv6 port : ' server_portv6
read -p 'View distance: ' view_distance
read -p 'Max threads: ' max_threads
read -p 'Level name: ' level_name
read -p 'Level seed: ' level_seed

echo ""
echo "Saving configuration..."

server_properties="$(cat instances/${instance_name}/server.properties)"
server_properties=`sed -e "s/^server-name=.*$/server-name=${server_name}/" <<< "${server_properties}"`
server_properties=`sed -e "s/^gamemode=.*$/gamemode=${game_mode}/" <<< "${server_properties}"`
server_properties=`sed -e "s/^difficulty=.*$/difficulty=${difficulty}/" <<< "${server_properties}"`
server_properties=`sed -e "s/^allow-cheats=.*$/allow-cheats=${allow_cheats}/" <<< "${server_properties}"`
server_properties=`sed -e "s/^server-port=.*$/server-port=${server_port}/" <<< "${server_properties}"`
server_properties=`sed -e "s/^server-portv6=.*$/server-portv6=${server_portv6}/" <<< "${server_properties}"`
server_properties=`sed -e "s/^view-distance=.*$/view-distance=${view_distance}/" <<< "${server_properties}"`
server_properties=`sed -e "s/^max-threads=.*$/max-threads=${max_threads}/" <<< "${server_properties}"`
server_properties=`sed -e "s/^level-name=.*$/level-name=${level_name}/" <<< "${server_properties}"`
server_properties=`sed -e "s/^level-seed=.*$/level-seed=${level_seed}/" <<< "${server_properties}"`

printf "%s\n" "$server_properties" > "instances/${instance_name}/server.properties"

echo "server.properties has been saved."

echo ""
echo "Bedrock Server new instance creation completed."
echo "To create, enable and start the systemd service for <${instance_name}>, run:"
echo ""
echo "  sudo ./install-service ${instance_name}"
echo ""
